apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrdapplication
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hrdapplication
  template:
    metadata:
      labels:
        app: hrdapplication
    spec:
      containers:
      - name: hrdapplication
        image: ketan897654/hrdapplication:latest
        ports:
        - containerPort: 8056